[profile.default]
src = "src"
out = "out"
libs = ["../lib", "../dependencies"]
solc_version = "0.8.31"
ignored_error_codes = [2424]
auto_detect_remappings = false
remappings = [
    "@openzeppelin/contracts-upgradeable/=../lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=../lib/openzeppelin-contracts/contracts/",
    "forge-std/=../lib/forge-std/src/",
    "openzeppelin-foundry-upgrades/=../lib/openzeppelin-foundry-upgrades/src/"
]
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
local = "http://127.0.0.1:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
