[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib", "dependencies"]
test = "test"
cache_path = "cache"
solc = "0.8.31"
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = false
remappings_location = "txt"
recursive_deps = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
override_spacing = false
wrap_comments = false
ignore = [
    "*/node_modules/**",
    "*/artifacts/**",
    "*/cache/**",
    "*/lib/**",
    "*/dependencies/**"
]

[dependencies]
forge-std = "1.12.0"
"@openzeppelin-contracts" = "5.5.0"
"@openzeppelin-contracts-upgradeable" = "5.5.0"
openzeppelin-foundry-upgrades = "0.4.0"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
